# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c711415c04b327117d20cf55f69a9a274b8765804e5ca887b3f4d50761139aa89e18d812e439eb220ddcc964a62dc39c44f8bd5242b58269cffbe1a4207205c5

test:
  secret_key_base: 52c5e77b2f33054ca8d027459c74fdca4f221f54785a575b5b64dfacb92ac2ab0bccffa3985d757409069852c0243f27cdc309381d178923f277ad16179d37ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
